# Generated by Django 2.2.14 on 2021-09-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210907_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dated_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
