# Generated by Django 2.2.14 on 2021-09-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210829_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comlete',
        ),
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
