# Generated by Django 2.2.14 on 2021-09-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210921_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='decription',
            field=models.CharField(max_length=200),
        ),
    ]
